Repository Geoxor/Shaii, pull requests merged in 2021-12, with the labels that each got.

#65 added back new actions script
  .github/workflows/push.yml
Labels: tests

#66 Fixed issue + re-added few commands
  src/commands/fun/say.shaii.ts
  src/commands/index.ts
  src/constants/index.ts
  src/middleware/commandMiddleware.shaii.ts
Labels: improvement, bug fix

#74 improve say command + message when command not found
  package-lock.json
  package.json
  src/commands/fun/say.shaii.ts
  src/example.config.shaii.json
  src/shaii/Shaii.shaii.ts
Labels: bug fix

#77 2 new commands + small refactor on text commands
  src/commands/index.ts
  src/commands/textProcessors/brainfuck.shaii.ts
  src/commands/textProcessors/britify.shaii.ts
  src/commands/textProcessors/spongify.shaii.ts
  src/commands/textProcessors/textify.shaii.ts
  src/commands/textProcessors/uwufy.shaii.ts
  src/logic/logic.shaii.ts
  src/logic/textProcessors.shaii.ts
  src/tests/logic.test.ts
  src/types.ts
Labels: improvement

#78 actually log database connection errors
  src/shaii/Database.shaii.ts
Labels: bug

#82 removes discord invite links
  src/middleware/moderationMiddleware.shaii.ts
  src/moderation/isDiscordInvite.ts
Labels: improvement

#91 Grammar nazi
  package-lock.json
  src/commands/economyGames/battle.shaii.ts
  src/commands/fun/dicksize.shaii.ts
  src/commands/fun/match.shaii.ts
  src/commands/fun/say.shaii.ts
  src/commands/imageProcessors/stack.shaii.ts
  src/commands/imageProcessors/transform.shaii.ts
  src/commands/moderation/ban.shaii.ts
  src/commands/moderation/kick.shaii.ts
  src/commands/moderation/mute.shaii.ts
  src/commands/moderation/unmute.shaii.ts
  src/commands/moderation/whois.shaii.ts
  src/commands/musicPlayer/shuffle.shaii.ts
  src/commands/textProcessors/brainfuck.shaii.ts
  src/commands/textProcessors/britify.shaii.ts
  src/commands/textProcessors/spongify.shaii.ts
  src/commands/textProcessors/textify.shaii.ts
  src/constants/index.ts
  src/logic/3DRenderer.shaii.ts
  src/logic/logic.shaii.ts
  src/middleware/musicMiddleware.shaii.ts
  src/shaii.ts
  src/shaii/Config.shaii.ts
  src/shaii/Database.shaii.ts
  src/shaii/MusicPlayer.shaii.ts
  src/shaii/Shaii.shaii.ts
  src/shaii/WaifuBattle.shaii.ts
  src/tests/logic.test.ts
Labels: improvement

#93 Added auto-capitalization to command names
  src/logic/logic.shaii.ts
Labels: improvement, bug fix
